# Use an official Python runtime as a parent image
FROM ubuntu:jammy

# Set the working directory
WORKDIR /capsule

# Copy the current directory contents into the container at /capsule
COPY . /capsule

# Install any dependencies specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt